//PRINT NATURAN N NO;


#include<iostream>
using namespace std;


// int main(){
//     int n,i;
    

// cout<<"enter value of n";
// cin>>n;

//     for(i=1;i<=n;i++){
//         cout<<i<<endl;
//     }
 
//   return 0;
// }


// question2 sum of tu no



// int main(){
//     int a,b;
//     cout<<"enter vale of a ,b"<<endl;
//     cin>>a>>b;
//     cout<<"ans is "<<a+b;



// }







// int main(){
//     int n;
//     int i=0;
//     cout<<"enter the value of n";
//     cin>>n;
//   while(i<=10)
// {
//     i++;
//     cout<<i*n;
// }
// }